// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HostKeyChangedInfo = { host: string, port: number, fingerprint_offered: string, fingerprint_known: string, 
/**
 * 1-indexed line number in the known_hosts file where the conflict was found.
 */
known_hosts_line: number, };
