// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptsDirInfo } from "./TranscriptsDirInfo";
import type { VizItem } from "./VizItem";
import type { Watch } from "./Watch";

export type InitialState = { watches: Array<Watch>, items: Array<VizItem>, follow_latest: boolean, selected: [string, string] | null, transcripts_dir: TranscriptsDirInfo, };
