// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One past remote connection. The dedup key is the full tuple — same host, different paths
 * stay as separate chips because users routinely watch multiple folders on one box.
 */
export type RecentRemote = { host: string, user: string, port: number, remote_path: string, glob: string, last_used_ms: number, };
