// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemoteDirListing = { current: string, parent: string | null, entries: Array<string>, next_cursor: string | null, total_estimate: number | null, };
