// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SshHostEntry = { alias: string, host_name: string, user: string | null, port: number, };
