// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TestStage } from "./TestStage";

export type TestResult = { reachable: TestStage, authenticated: TestStage, path_exists: TestStage, matched: TestStage, };
