// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostKeyChangedInfo } from "./HostKeyChangedInfo";
import type { TestStage } from "./TestStage";
import type { UnknownHostInfo } from "./UnknownHostInfo";

export type TestResult = { reachable: TestStage, authenticated: TestStage, path_exists: TestStage, matched: TestStage, 
/**
 * Set when the host key isn't in known_hosts. Frontend should prompt the user to trust.
 */
unknown_host: UnknownHostInfo | null, 
/**
 * Set when known_hosts already has a different (or revoked) key for this host. The
 * frontend should NOT offer a trust path — only `ssh-keygen -R` advice.
 */
host_key_changed: HostKeyChangedInfo | null, };
