// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TestStage = { ok: boolean, error: string | null, matched_files: number | null, };
