// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptsDirSource } from "./TranscriptsDirSource";

/**
 * Snapshot of the local transcripts directory state. Sent to the frontend on hydrate and
 * after `set_claude_history_path` so the Settings dialog and the missing/empty banner
 * always reflect what the backend resolver actually picked.
 */
export type TranscriptsDirInfo = { 
/**
 * The user-set override from prefs.json, verbatim. None if no override.
 */
override_path: string | null, 
/**
 * The absolute path the resolver picked after running the precedence chain.
 */
resolved_path: string, source: TranscriptsDirSource, 
/**
 * Filesystem check: does `resolved_path` exist as a directory right now?
 */
exists: boolean, 
/**
 * True iff `resolved_path` exists AND contains at least one .jsonl file in any
 * immediate subdirectory. Used to surface "configured but empty" as a banner.
 */
has_jsonl: boolean, };
