// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the resolved local transcripts root came from. Drives the Settings dialog placeholder
 * label so users can see at a glance whether their `CLAUDE_CONFIG_DIR` is being honored.
 */
export type TranscriptsDirSource = "override" | "env" | "default";
