// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UnknownHostInfo = { host: string, port: number, 
/**
 * SHA256:<base64> form, ready to display.
 */
fingerprint: string, 
/**
 * e.g. "ssh-ed25519", "ecdsa-sha2-nistp256".
 */
key_type: string, 
/**
 * The full OpenSSH-formatted public key line ("<algo> <base64> [comment]").
 */
raw_openssh: string, };
