// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VizEnriched = { watch_id: string, abs_path: string, prompt: string, tool_use_id: string | null, };
