// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VizUpdated = { watch_id: string, abs_path: string, mtime: number, size: number, };
