// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WatchStatus = { "kind": "connected" } | { "kind": "reconnecting", since_ms: number, last_error: string | null, } | { "kind": "auth_failed", last_error: string, } | { "kind": "unreachable", since_ms: number, last_error: string, } | { "kind": "path_invalid", last_error: string, } | { "kind": "stopped" };
