// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WatchSource = { "kind": "local", path: string, } | { "kind": "ssh", host: string, user: string, port: number, remote_path: string, glob: string, };
