// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WatchSource } from "./WatchSource";

export type Watch = { id: string, source: WatchSource, session_path: string | null, };
