// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WatchStatus } from "./WatchStatus";

export type WatchStatusEvent = { watch_id: string, status: WatchStatus, };
