// Generated by ts-rs from src-tauri/src/types.rs and src-tauri/src/cap.rs.
// Run `cd src-tauri && cargo test` to regenerate src/types/bindings/*.

export type { VizItem } from "./types/bindings/VizItem";
export type { VizKind } from "./types/bindings/VizKind";
export type { VizStatus } from "./types/bindings/VizStatus";
export type { VizUpdated } from "./types/bindings/VizUpdated";
export type { VizEnriched } from "./types/bindings/VizEnriched";
export type { VizGone } from "./types/bindings/VizGone";
export type { VizEvicted } from "./types/bindings/VizEvicted";
export type { WatchSource } from "./types/bindings/WatchSource";
export type { Watch } from "./types/bindings/Watch";
export type { InitialState } from "./types/bindings/InitialState";
export type { WatchStatus } from "./types/bindings/WatchStatus";
export type { WatchStatusEvent } from "./types/bindings/WatchStatusEvent";
export type { SshHostEntry } from "./types/bindings/SshHostEntry";
export type { SshAgentProbe } from "./types/bindings/SshAgentProbe";
export type { TestResult } from "./types/bindings/TestResult";
export type { TestStage } from "./types/bindings/TestStage";
export type { UnknownHostInfo } from "./types/bindings/UnknownHostInfo";
export type { HostKeyChangedInfo } from "./types/bindings/HostKeyChangedInfo";
export type { RecentRemote } from "./types/bindings/RecentRemote";
export type { RemoteDirListing } from "./types/bindings/RemoteDirListing";

export type ItemId = string;
export const itemId = (watch_id: string, abs_path: string): ItemId =>
  `${watch_id}::${abs_path}`;
