// Generated by ts-rs from src-tauri/src/types.rs and src-tauri/src/cap.rs.
// Run `cd src-tauri && cargo test` to regenerate src/types/bindings/*.

export type { VizItem } from "./types/bindings/VizItem";
export type { VizKind } from "./types/bindings/VizKind";
export type { VizStatus } from "./types/bindings/VizStatus";
export type { VizUpdated } from "./types/bindings/VizUpdated";
export type { VizEnriched } from "./types/bindings/VizEnriched";
export type { VizGone } from "./types/bindings/VizGone";
export type { VizEvicted } from "./types/bindings/VizEvicted";
export type { WatchSource } from "./types/bindings/WatchSource";
export type { Watch } from "./types/bindings/Watch";
export type { InitialState } from "./types/bindings/InitialState";

export type ItemId = string;
export const itemId = (watch_id: string, abs_path: string): ItemId =>
  `${watch_id}::${abs_path}`;
